name: 🚀 Feature Request
description: Suggest an idea
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a Feature Request!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com///issues) to see if a similar feature request already exists.
      options:
        - label: >
            I have searched the [issues](https://github.com///issues) and found no similar feature requests.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature.
      placeholder: |
        What new feature would you like to see?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case
      description: |
        Describe the use case of your feature request. It will help us understand and prioritize the feature request.
      placeholder: |
        How would this feature be used, and who would use it?

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?
